config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :pictures
  end

  resources :pictures do
    resources :tags
  end

  root to: "users#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :manage, Picture, :user => { :id => user.id } 
      end
      can :destroy, Picture do |image|
        image.try(:user) == user
      end
      can :edit, Picture do |image|
        image.try(:user) == user
      end
      #
      # can :edit, Picture do |image|
      #

    end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  has_many :tags

  has_attached_file :image, :styles => { :medium => "300x300>", :large => "500x500>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/default-user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def admin?
    self.role == "Admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "Access denied!"
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :avatar)}

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :avatar)}
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  load_and_authorize_resource :through => :users
  before_filter :authenticate_user!, except: [:index, :show]


  def index
    @pictures = Picture.all
  end

  def show
    @user = User.find(params[:user_id])
    # @picture = Picture.find(params[:id])
    @tag = Tag.find(params[:id])
  end

  def new
    @user = current_user
    @picture = current_user.pictures.build
  end

  def edit
    @user = User.find(params[:user_id])
    # @picture = Picture.find(params[:id])
  end

  def destroy
    # @picture = Picture.find(params[:id])
    @picture.destroy
      redirect_to user_path(current_user), notice: "Your picture is gone forever!"
  end

  def update
    @user = User.find(params[:user_id])
    # @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to user_path(current_user), notice: "Changes sucessfully made"
    else
      render :edit
    end
  end

  def create
    @user = current_user
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to user_path(@user), notice: "Your picture was successfully uploaded."
    else
      render :new
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :image)
  end

end

app/controllers/roles_controller.rb
class RolesController <ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @roles = Role.all
  end

  def show
    if @role.users.length == 0
      @associated_users = "None"
    else
      @associated_users = @role.users.map(&:name).join(", ")
    end
  end

  def new
  end

  def edit
  end

  def create
  end

  private

  def role_params
    params.require(:role).permit(:name, :description)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @picture = Picture.find(params[:picture_id])
    @tag = @picture.tags.new
  end

  def create
    @picture = Picture.find(params[:picture_id])
    @user = @picture.user_id
    @tag = @picture.tags.create(tag_params)
    if @tag.save
      redirect_to user_picture_path(@user, @picture)
    end
  end

  def show
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end



end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def create
  @user = User.create( user_params )
end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def user_params
  params.require(:user).permit(:avatar)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!


  def index
    @pictures = Picture.all
  end

  def create
  @user = User.create( user_params )
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:avatar)
  end


  def show
    @user = current_user
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickrClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <nav class="navbar navbar-default">
    <div class="container-fluid">
        <%= link_to 'Flickresque', root_path, class: "navbar-brand"  %>
      <div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href="<%= user_path(current_user) %>">Logged in as <strong><%= current_user.email %></a></strong></a></li>
            <li><%= link_to 'Upload Photos', new_user_picture_path(current_user) %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <li class='round-image-50'><%= image_tag(current_user.avatar.url(:thumb)) %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %> </li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>





  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pictures/edit.html.erb
<%= form_for [@user, @picture] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Title' %>
  <%= f.submit 'Submit Changes' %>
<% end %>

app/views/pictures/new.html.erb
<%= form_for [@user, @picture] do |f| %>
<%= f.label :title %>
<%= f.text_field :title, placeholder: 'Title' %>
<%= f.label :image %>
<%= f.file_field :image %>
<%= f.submit 'Upload', id: 'fileUpload', data: { disable_with: 'Uploading' } %>
<% end %>

app/views/pictures/show.html.erb
<h2><%= @picture.title %></h2>
<hr>

<%= image_tag(@picture.image.url(:large)) %>
<% @picture.tags.each do |tag| %>
  <%= tag.name %>,
  <% end %>

<%= link_to "Add Tags", new_picture_tag_path(@picture) %>

  <% if current_user %>
| <%= link_to "Edit", edit_user_picture_path(@picture.user_id, @picture) %> |
<%= link_to "Delete", user_picture_path(@picture.user_id, @picture), method: :delete %>
<% end %>

app/views/tags/new.html.erb
<%= form_for [@picture, @tag] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.submit 'Tag Photo' %>
<% end %>

app/views/users/index.html.erb
<% @pictures.each do |image| %>

<ul>
  <a href="<%= user_picture_path(image.user_id, image) %>"><%= image_tag(image.image.url(:medium)) %></a>
  <%= image.title %>
</ul>

<% end %>

app/views/users/show.html.erb
<% current_user.pictures.each do |image| %>
<ul>
  <a href="<%= user_picture_path(current_user, image) %>"><%= image_tag(image.image.url(:medium)) %></a>
  <%= image.title %>
  <% if can? :update, @picture %>
  | <%= link_to "Edit", edit_user_picture_path(image.user_id, image) %> |
  <% end %>
  <% if can? :update, @picture %>
  <%= link_to "Delete", user_picture_path(image.user_id, image), method: :delete %>
  <% end %>


</ul>
<% end %>